name: "$(Date:yyyy)-$(Date:MM)-$(Rev:r)"

pr:
- main

trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

jobs:
- job: build
  displayName: Build
  steps:

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: static-app 
      dockerfile: $(Build.SourcesDirectory)/Dockerfile 
      containerRegistry: acr-wg
      tags: |
        $(Build.BuildNumber)
